function FF4Rom.DecompressDTE(text as String) as String
 dim result as String
 dim symbol as UByte
 for i as Integer = 1 to len(text)
  symbol = asc(mid(text, i, 1))
  if cbool(i < len(text)) and MessageParameter(symbol) then
   result += chr(symbol) + mid(text, i, 1)
   i += 1
  else
   select case symbol
   case &h8A: result += ConvertText("e ")
   case &h8B: result += ConvertText(" t")
   case &h8C: result += ConvertText("th")
   case &h8D: result += ConvertText("he")
   case &h8E: result += ConvertText("t ")
   case &h8F: result += ConvertText("ou")
   case &h90: result += ConvertText(" a")
   case &h91: result += ConvertText("s ")
   case &h92: result += ConvertText("er")
   case &h93: result += ConvertText("in")
   case &h94: result += ConvertText("re")
   case &h95: result += ConvertText("d ")
   case &h96: result += ConvertText("an")
   case &h97: result += ConvertText(" o")
   case &h98: result += ConvertText("on")
   case &h99: result += ConvertText("st")
   case &h9A: result += ConvertText(" w")
   case &h9B: result += ConvertText("o ")
   case &h9C: result += ConvertText(" m")
   case &h9D: result += ConvertText("ha")
   case &h9E: result += ConvertText("to")
   case &h9F: result += ConvertText("is")
   case &hA0: result += ConvertText("yo")
   case &hA1: result += ConvertText(" y")
   case &hA2: result += ConvertText(" i")
   case &hA3: result += ConvertText("al")
   case &hA4: result += ConvertText("ar")
   case &hA5: result += ConvertText(" h")
   case &hA6: result += ConvertText("r ")
   case &hA7: result += ConvertText(" s")
   case &hA8: result += ConvertText("at")
   case &hA9: result += ConvertText("n ")
   case &hAA: result += ConvertText(" c")
   case &hAB: result += ConvertText("ng")
   case &hAC: result += ConvertText("ve")
   case &hAD: result += ConvertText("ll")
   case &hAE: result += ConvertText("y ")
   case &hAF: result += ConvertText("nd")
   case &hB0: result += ConvertText("en")
   case &hB1: result += ConvertText("ed")
   case &hB2: result += ConvertText("hi")
   case &hB3: result += ConvertText("or")
   case &hB4: result += ConvertText(", ")
   case &hB5: result += ConvertText("I ")
   case &hB6: result += ConvertText("u ")
   case &hB7: result += ConvertText("me")
   case &hB8: result += ConvertText("ta")
   case &hB9: result += ConvertText(" b")
   case &hBA: result += ConvertText(" I")
   case &hBB: result += ConvertText("te")
   case &hBC: result += ConvertText("of")
   case &hBD: result += ConvertText("ea")
   case &hBE: result += ConvertText("ur")
   case &hBF: result += ConvertText("l ")
   'C0 through C9 aren't DTE
   case &hCA: result += ConvertText(" f")
   case &hCB: result += ConvertText(" d")
   case &hCC: result += ConvertText("ow")
   case &hCD: result += ConvertText("se")
   case &hCE: result += ConvertText("  ")
   case &hCF: result += ConvertText("it")
   case &hD0: result += ConvertText("et")
   case &hD1: result += ConvertText("le")
   case &hD2: result += ConvertText("f ")
   case &hD3: result += ConvertText(" g")
   case &hD4: result += ConvertText("es")
   case &hD5: result += ConvertText("ro")
   case &hD6: result += ConvertText("ne")
   case &hD7: result += ConvertText("ry")
   case &hD8: result += ConvertText(" l")
   case &hD9: result += ConvertText("us")
   case &hDA: result += ConvertText("no")
   case &hDB: result += ConvertText("ut")
   case &hDC: result += ConvertText("ca")
   case &hDD: result += ConvertText("as")
   case &hDE: result += ConvertText("Th")
   case &hDF: result += ConvertText("ai")
   case &hE0: result += ConvertText("ot")
   case &hE1: result += ConvertText("be")
   case &hE2: result += ConvertText("el")
   case &hE3: result += ConvertText("om")
   case &hE4: result += ConvertText("'s")
   case &hE5: result += ConvertText("il")
   case &hE6: result += ConvertText("de")
   case &hE7: result += ConvertText("gh")
   case &hE8: result += ConvertText("ay")
   case &hE9: result += ConvertText("nt")
   case &hEA: result += ConvertText("Wh")
   case &hEB: result += ConvertText("Yo")
   case &hEC: result += ConvertText("wa")
   case &hED: result += ConvertText("oo")
   case &hEE: result += ConvertText("We")
   case &hEF: result += ConvertText("g ")
   case &hF0: result += ConvertText("ge")
   case &hF1: result += ConvertText(" n")
   case &hF2: result += ConvertText("ee")
   case &hF3: result += ConvertText("wi")
   case &hF4: result += ConvertText(" M")
   case &hF5: result += ConvertText("ke")
   case &hF6: result += ConvertText("we")
   case &hF7: result += ConvertText(" p")
   case &hF8: result += ConvertText("ig")
   case &hF9: result += ConvertText("ys")
   case &hFA: result += ConvertText(" B")
   case &hFB: result += ConvertText("am")
   case &hFC: result += ConvertText("ld")
   case &hFD: result += ConvertText(" W")
   case &hFE: result += ConvertText("la")
   case else: result += chr(symbol)
   end select
  end if
 next
 return result
end function
