sub FF4Rom.InitializeStatusNames()

 element_names.Destroy()
 persistent_status_names.Destroy()
 temporary_status_names.Destroy()
 hidden_status_names.Destroy()
 system_status_names.Destroy()
 
 element_names.AddItem("fire")
 element_names.AddItem("ice")
 element_names.AddItem("bolt")
 element_names.AddItem("dark")
 element_names.AddItem("holy")
 element_names.AddItem("air")
 element_names.AddItem("absorb")
 element_names.AddItem("immune")
 
 persistent_status_names.AddItem("poison")
 persistent_status_names.AddItem("blind")
 persistent_status_names.AddItem("mute")
 persistent_status_names.AddItem("pig")
 persistent_status_names.AddItem("mini")
 persistent_status_names.AddItem("frog")
 persistent_status_names.AddItem("petrify")
 persistent_status_names.AddItem("ko")
 
 temporary_status_names.AddItem("calcify1")
 temporary_status_names.AddItem("calcify2")
 temporary_status_names.AddItem("berserk")
 temporary_status_names.AddItem("charm")
 temporary_status_names.AddItem("sleep")
 temporary_status_names.AddItem("stun")
 temporary_status_names.AddItem("float")
 temporary_status_names.AddItem("curse")
 
 hidden_status_names.AddItem("count")
 hidden_status_names.AddItem("airborne")
 hidden_status_names.AddItem("twincasting")
 hidden_status_names.AddItem("charging")
 hidden_status_names.AddItem("defending")
 hidden_status_names.AddItem("egg")
 hidden_status_names.AddItem("stop")
 hidden_status_names.AddItem("magnetized")
 
 system_status_names.AddItem("critical")
 system_status_names.AddItem("covered")
 system_status_names.AddItem("blink1")
 system_status_names.AddItem("blink2")
 system_status_names.AddItem("barrier")
 system_status_names.AddItem("reflect")
 system_status_names.AddItem("hpleak")
 system_status_names.AddItem("hiding")

end sub
