sub FF4Rom.InitializeInstructionNames()

 instruction_names.Destroy()

 for i as Integer = 0 to 11
  instruction_names.AddItem(str(i) + "moves up")
  instruction_names.AddItem(str(i) + "moves right")
  instruction_names.AddItem(str(i) + "moves down")
  instruction_names.AddItem(str(i) + "moves left")
  instruction_names.AddItem(str(i) + "faces up")
  instruction_names.AddItem(str(i) + "faces right")
  instruction_names.AddItem(str(i) + "faces down")
  instruction_names.AddItem(str(i) + "faces left")
  instruction_names.AddItem(str(i) + "toggles visibility")
  instruction_names.AddItem(str(i) + "jumps")
  instruction_names.AddItem(str(i) + "spins")
  instruction_names.AddItem(str(i) + "hops")
  instruction_names.AddItem(str(i) + "waves in")
  instruction_names.AddItem(str(i) + "waves out")
  instruction_names.AddItem(str(i) + "bows head")
  instruction_names.AddItem(str(i) + "lies down")
 next
 
 instruction_names.AddItem("you move up")
 instruction_names.AddItem("you move right")
 instruction_names.AddItem("you move down")
 instruction_names.AddItem("you move left")
 instruction_names.AddItem("you face up")
 instruction_names.AddItem("you face right")
 instruction_names.AddItem("you face down")
 instruction_names.AddItem("you face left")
 instruction_names.AddItem("you disappear")
 instruction_names.AddItem("you appear")
 instruction_names.AddItem("you wave in")
 instruction_names.AddItem("you wave out")
 instruction_names.AddItem("you bow head")
 instruction_names.AddItem("you lie down")
 instruction_names.AddItem("you freeze")
 instruction_names.AddItem("you spin")
 
 instruction_names.AddItem("rumble")
 instruction_names.AddItem("flash")
 instruction_names.AddItem("blur")
 instruction_names.AddItem("moon")
 instruction_names.AddItem("fat chocobo")
 instruction_names.AddItem("door")
 instruction_names.AddItem("shake")
 instruction_names.AddItem("run")
 instruction_names.AddItem("music fade")
 instruction_names.AddItem("namingway")
 instruction_names.AddItem("screen fade")
 instruction_names.AddItem("toggle status")
 instruction_names.AddItem("pay money")
 instruction_names.AddItem("set leader")
 instruction_names.AddItem("restore hp")
 instruction_names.AddItem("restore mp")
 instruction_names.AddItem("gain item")
 instruction_names.AddItem("lose item")
 instruction_names.AddItem("learn spell")
 instruction_names.AddItem("lose status")
 instruction_names.AddItem("gain status")
 instruction_names.AddItem("gain money")
 instruction_names.AddItem("lose money")
 instruction_names.AddItem("actor joins")
 instruction_names.AddItem("actor leaves")
 instruction_names.AddItem("pause")
 instruction_names.AddItem("fade in song")
 instruction_names.AddItem("repeat concurrent actions")
 instruction_names.AddItem("fight battle")
 instruction_names.AddItem("shop")
 instruction_names.AddItem("bank 2 parameter")
 instruction_names.AddItem("bank 2")
 instruction_names.AddItem("bank 1 low")
 instruction_names.AddItem("bank 1 high")
 instruction_names.AddItem("set flag")
 instruction_names.AddItem("clear flag")
 instruction_names.AddItem("activate npc")
 instruction_names.AddItem("deactivate npc")
 instruction_names.AddItem("bank 3")
 instruction_names.AddItem("select item")
 instruction_names.AddItem("yes/no box")
 instruction_names.AddItem("screen tint")
 instruction_names.AddItem("play song")
 instruction_names.AddItem("sound effect")
 instruction_names.AddItem("crash game")
 instruction_names.AddItem("special effect")
 instruction_names.AddItem("teleport")
 instruction_names.AddItem("end")

end sub
